// Translations for the Contact Us and About Us screens (English, Hindi,
// Gujarati). Kept in their own file so the two big screens' copy is easy to
// find and replace — the About Us numbers/milestones are dummy content for
// now (see `about_us_data.dart`).

const infoPagesEn = <String, String>{
  // ---- Contact Us ----
  'contact_hero_title': "We're here to help",
  'contact_hero_subtitle': 'Reach the Foundation team for membership, payments or any question.',
  'contact_call_office': 'Call office',
  'contact_reach_us': 'Our team',
  'contact_role_office': 'Foundation Office',
  'contact_role_founder': 'Founder & Director',
  'contact_open_now': 'Open now',
  'contact_closed_now': 'Closed now',
  'contact_email_title': 'Email us',
  'contact_send_email': 'Send email',
  'contact_visit_us': 'Visit us',
  'contact_reg_office': 'Registered office',
  'contact_founders_office': "Founders' office",
  'contact_reg_office_address': '57, D.K. Nagar-2, Nr. Santoshi Krupa Society, Dabholi Char Rasta, Katargam, Surat - 395 004',
  'contact_founders_office_address': 'B/29, Second Floor, Danev Ashish Society, Chikuwadi Road, Katargam, Surat - 395 004',
  'contact_open_in_maps': 'Open in Maps',

  // ---- About Us ----
  'about_hero_tagline': 'A true promise of family security',
  'about_since': 'Since 2025',
  'about_stat_families': 'Families supported',
  'about_stat_members': 'Members',
  'about_stat_districts': 'Districts',
  'about_stat_programs': 'Programs',
  'about_who_we_are_title': 'Who we are',
  'about_who_we_are_text':
      'Parivar Suraksha Foundation is a non-profit organisation working to give every family a safety net — through member-supported schemes, timely help in difficult moments and awareness programs.',
  'about_what_we_do_title': 'What we do',
  'about_program_health_title': 'Health support',
  'about_program_health_text': 'Help with medical needs and health awareness for member families.',
  'about_program_education_title': 'Education aid',
  'about_program_education_text': "Support for children's schooling and skill building.",
  'about_program_family_title': 'Family security',
  'about_program_family_text': 'A dependable safety net for nominees in times of need.',
  'about_program_community_title': 'Community welfare',
  'about_program_community_text': 'Social programs that bring families and neighbourhoods together.',
  'about_journey_title': 'Our journey',
  'about_milestone_1_title': 'Foundation established',
  'about_milestone_1_text': 'Registered as a non-profit company in Surat.',
  'about_milestone_2_title': 'Member scheme launched',
  'about_milestone_2_text': 'The first membership scheme opened for families.',
  'about_milestone_3_title': 'Mobile app launched',
  'about_milestone_3_text': 'Members can now manage everything from their phone.',
  'about_leaders_title': 'Leadership',
  'about_reg_title': 'Registration details',
  'about_reg_cin': 'Registration No. (CIN)',
  'about_reg_licence': 'Licence No.',
  'about_cta_title': 'Have a question?',
  'about_cta_text': 'Our team is happy to help you.',
};

const infoPagesHi = <String, String>{
  // ---- Contact Us ----
  'contact_hero_title': 'हम आपकी मदद के लिए हैं',
  'contact_hero_subtitle': 'सदस्यता, भुगतान या किसी भी प्रश्न के लिए फाउंडेशन टीम से संपर्क करें।',
  'contact_call_office': 'कार्यालय को कॉल करें',
  'contact_reach_us': 'हमारी टीम',
  'contact_role_office': 'फाउंडेशन कार्यालय',
  'contact_role_founder': 'संस्थापक एवं निदेशक',
  'contact_open_now': 'अभी खुला है',
  'contact_closed_now': 'अभी बंद है',
  'contact_email_title': 'हमें ईमेल करें',
  'contact_send_email': 'ईमेल भेजें',
  'contact_visit_us': 'हमसे मिलें',
  'contact_reg_office': 'पंजीकृत कार्यालय',
  'contact_founders_office': 'संस्थापकों का कार्यालय',
  'contact_reg_office_address': '57, डी.के. नगर-2, संतोषी कृपा सोसायटी के पास, डभोली चार रास्ता, कतारगाम, सूरत - 395 004',
  'contact_founders_office_address': 'बी/29, दूसरी मंज़िल, दानेव आशीष सोसायटी, चीकूवाड़ी रोड, कतारगाम, सूरत - 395 004',
  'contact_open_in_maps': 'मैप में खोलें',

  // ---- About Us ----
  'about_hero_tagline': 'परिवार की सुरक्षा का सच्चा वचन',
  'about_since': '2025 से',
  'about_stat_families': 'सहायता प्राप्त परिवार',
  'about_stat_members': 'सदस्य',
  'about_stat_districts': 'जिले',
  'about_stat_programs': 'योजनाएँ',
  'about_who_we_are_title': 'हम कौन हैं',
  'about_who_we_are_text':
      'परिवार सुरक्षा फाउंडेशन एक गैर-लाभकारी संस्था है, जो सदस्यों द्वारा समर्थित योजनाओं, कठिन समय में समय पर सहायता और जागरूकता कार्यक्रमों के माध्यम से हर परिवार को सुरक्षा कवच देने का काम करती है।',
  'about_what_we_do_title': 'हम क्या करते हैं',
  'about_program_health_title': 'स्वास्थ्य सहायता',
  'about_program_health_text': 'सदस्य परिवारों के लिए चिकित्सा जरूरतों और स्वास्थ्य जागरूकता में सहायता।',
  'about_program_education_title': 'शिक्षा सहायता',
  'about_program_education_text': 'बच्चों की पढ़ाई और कौशल विकास के लिए सहयोग।',
  'about_program_family_title': 'पारिवारिक सुरक्षा',
  'about_program_family_text': 'जरूरत के समय वारिसों के लिए भरोसेमंद सुरक्षा कवच।',
  'about_program_community_title': 'सामुदायिक कल्याण',
  'about_program_community_text': 'परिवारों और समाज को जोड़ने वाले सामाजिक कार्यक्रम।',
  'about_journey_title': 'हमारी यात्रा',
  'about_milestone_1_title': 'फाउंडेशन की स्थापना',
  'about_milestone_1_text': 'सूरत में गैर-लाभकारी कंपनी के रूप में पंजीकृत।',
  'about_milestone_2_title': 'सदस्य योजना शुरू',
  'about_milestone_2_text': 'परिवारों के लिए पहली सदस्यता योजना शुरू।',
  'about_milestone_3_title': 'मोबाइल ऐप लॉन्च',
  'about_milestone_3_text': 'अब सदस्य सब कुछ अपने फ़ोन से संभाल सकते हैं।',
  'about_leaders_title': 'नेतृत्व',
  'about_reg_title': 'पंजीकरण विवरण',
  'about_reg_cin': 'पंजीकरण क्र. (CIN)',
  'about_reg_licence': 'लाइसेंस क्र.',
  'about_cta_title': 'कोई प्रश्न है?',
  'about_cta_text': 'हमारी टीम आपकी मदद के लिए तैयार है।',
};

const infoPagesGu = <String, String>{
  // ---- Contact Us ----
  'contact_hero_title': 'અમે તમારી મદદ માટે છીએ',
  'contact_hero_subtitle': 'સભ્યપદ, ચુકવણી અથવા કોઈપણ પ્રશ્ન માટે ફાઉન્ડેશન ટીમનો સંપર્ક કરો.',
  'contact_call_office': 'ઓફિસને કૉલ કરો',
  'contact_reach_us': 'અમારી ટીમ',
  'contact_role_office': 'ફાઉન્ડેશન ઓફિસ',
  'contact_role_founder': 'સ્થાપક અને ડિરેક્ટર',
  'contact_open_now': 'હમણાં ખુલ્લું છે',
  'contact_closed_now': 'હમણાં બંધ છે',
  'contact_email_title': 'અમને ઈમેલ કરો',
  'contact_send_email': 'ઈમેલ મોકલો',
  'contact_visit_us': 'અમારી મુલાકાત લો',
  'contact_reg_office': 'રજિસ્ટર્ડ ઓફિસ',
  'contact_founders_office': 'સ્થાપકોની ઓફિસ',
  'contact_reg_office_address': '૫૭, ડી.કે. નગર-૨, સંતોષી કૃપા સોસાયટી પાસે, ડભોલી ચાર રસ્તા, કતારગામ, સુરત - ૩૯૫ ૦૦૪',
  'contact_founders_office_address': 'બી/૨૯, બીજો માળ, દાનેવ આશિષ સોસાયટી, ચીકુવાડી રોડ, કતારગામ, સુરત - ૩૯૫ ૦૦૪',
  'contact_open_in_maps': 'નકશામાં ખોલો',

  // ---- About Us ----
  'about_hero_tagline': 'પરિવારની સુરક્ષાનું સાચું વચન',
  'about_since': '૨૦૨૫ થી',
  'about_stat_families': 'સહાય મેળવેલા પરિવારો',
  'about_stat_members': 'સભ્યો',
  'about_stat_districts': 'જિલ્લાઓ',
  'about_stat_programs': 'યોજનાઓ',
  'about_who_we_are_title': 'અમે કોણ છીએ',
  'about_who_we_are_text':
      'પરિવાર સુરક્ષા ફાઉન્ડેશન એક બિન-નફાકારક સંસ્થા છે, જે સભ્યોના સહયોગથી ચાલતી યોજનાઓ, મુશ્કેલ સમયમાં સમયસર મદદ અને જાગૃતિ કાર્યક્રમો દ્વારા દરેક પરિવારને સુરક્ષા કવચ આપવાનું કામ કરે છે.',
  'about_what_we_do_title': 'અમે શું કરીએ છીએ',
  'about_program_health_title': 'આરોગ્ય સહાય',
  'about_program_health_text': 'સભ્ય પરિવારો માટે તબીબી જરૂરિયાતો અને આરોગ્ય જાગૃતિમાં સહાય.',
  'about_program_education_title': 'શિક્ષણ સહાય',
  'about_program_education_text': 'બાળકોના અભ્યાસ અને કૌશલ્ય વિકાસ માટે સહયોગ.',
  'about_program_family_title': 'પારિવારિક સુરક્ષા',
  'about_program_family_text': 'જરૂરના સમયે વારસદારો માટે ભરોસાપાત્ર સુરક્ષા કવચ.',
  'about_program_community_title': 'સમુદાય કલ્યાણ',
  'about_program_community_text': 'પરિવારો અને સમાજને જોડતા સામાજિક કાર્યક્રમો.',
  'about_journey_title': 'અમારી સફર',
  'about_milestone_1_title': 'ફાઉન્ડેશનની સ્થાપના',
  'about_milestone_1_text': 'સુરતમાં બિન-નફાકારક કંપની તરીકે નોંધણી.',
  'about_milestone_2_title': 'સભ્ય યોજના શરૂ',
  'about_milestone_2_text': 'પરિવારો માટે પ્રથમ સભ્યપદ યોજના શરૂ.',
  'about_milestone_3_title': 'મોબાઇલ એપ લોન્ચ',
  'about_milestone_3_text': 'હવે સભ્યો બધું પોતાના ફોનથી સંભાળી શકે છે.',
  'about_leaders_title': 'નેતૃત્વ',
  'about_reg_title': 'નોંધણી વિગતો',
  'about_reg_cin': 'નોંધણી નં. (CIN)',
  'about_reg_licence': 'લાઇસન્સ નં.',
  'about_cta_title': 'કોઈ પ્રશ્ન છે?',
  'about_cta_text': 'અમારી ટીમ તમારી મદદ માટે તૈયાર છે.',
};
