const registrationEn = <String, String>{
  'step': 'Step', 'personal_information': 'Personal information', 'personal_information_hint': 'Enter the details exactly as they appear on your documents.', 'date_of_birth': 'Date of birth', 'address': 'Address', 'aadhaar_number': 'Aadhaar number', 'gender': 'Gender', 'male': 'Male', 'female': 'Female', 'other': 'Other', 'profile_photo': 'Upload profile photo', 'aadhaar_photo': 'Upload Aadhaar card photo', 'file_selected': 'File selected', 'field_required': 'This field is required', 'invalid_number': 'Please enter a valid number', 'nominee_details': 'Nominee details', 'nominee_hint': 'Add the person who should receive benefits if needed.', 'nominee_name': 'Nominee name', 'relationship': 'Relationship', 'nominee_note': 'You can update nominee details later through support.', 'confirm_information': 'Confirm your information', 'confirm_information_hint': 'Please check all details before creating the application preview.', 'nominee_will_be_added': 'Nominee will be added on the next step', 'agree_terms': 'I confirm that the information above is correct and I agree to the scheme terms.', 'accept_terms_error': 'Please accept the terms to continue.', 'required': 'Required', 'preview_application': 'Preview application', 'application_preview': 'Application preview', 'download_pdf': 'Download PDF', 'download_from_server': 'Your original PDF will be downloaded from the server after submission.', 'complete_registration': 'Complete registration', 'beneficiary_application': 'Beneficiary application', 'page_count': 'Page @page of @total', 'declaration': 'Declaration', 'declaration_text': 'I declare that the information given in this application is true and complete. I understand that the Foundation will review the application before approval.', 'registration_submitted': 'Registration submitted!', 'registration_submitted_hint': 'Congratulations. Your application has been sent for approval.', 'approval_pending': 'Your application is under review', 'approval_pending_hint': 'We will notify you as soon as an administrator approves your registration.', 'approval_time': 'Approval time', 'approval_time_value': 'Usually 2-3 working days', 'support_contact': 'For help, please contact the Foundation support team.', 'support_office_hours_title': 'Office hours', 'support_office_hours_morning': 'Morning: 9:30 AM – 1:30 PM', 'support_office_hours_afternoon': 'Afternoon: 4:00 PM – 9:30 PM', 'support_contact_office_name': 'Office', 'support_contact_1_name': 'Bharat Variya', 'support_contact_2_name': 'Bipin Ghoghari', 'call': 'Call', 'whatsapp': 'WhatsApp', 'could_not_open_app_error': 'Could not open the app for this action.',

  // Member registration screen (step-1 UI + nominee + rules sub-steps)
  'member_registration': 'Member Registration',
  'full_name': 'Full Name',
  'full_name_hint': 'Enter First, Middle & Surname',
  'full_name_format_error': 'Enter First, Middle & Surname.',
  'father_name': 'Father Name',
  // Explains the exact First name + Surname format the field's validator
  // enforces (AppValidators.fatherName — exactly 2 words) — matches
  // father_name_format_error's wording so the hint and the error never
  // disagree with each other.
  'father_name_hint': 'Enter first name and surname',
  'father_name_format_error': 'Enter first name and surname.',
  'mobile_number': 'Mobile Number',
  'mobile_number_2': 'Mobile Number 2',
  'village': 'Village',
  'taluka': 'Taluka',
  'district': 'District',
  'state': 'State',
  'occupation': 'Occupation',
  'marital_status': 'Marital Status',
  'address_details': 'Address Details',
  'identity_documents': 'Identity Documents',
  'pan_number': 'PAN Number',
  'upload_pan_card': 'Upload PAN Card',
  'aadhaar_back_photo': 'Upload Aadhaar Back Photo',
  'tap_to_upload': 'Tap to upload',
  'tap_to_upload_image': 'Tap to upload image',
  'signature': 'Signature',
  'your_signature': 'Your Signature',
  'clear': 'Clear',
  'save_signature': 'Save Signature',
  'tap_to_enter_signature': 'Tap to enter signature',
  'nominee_photo': 'Nominee Photo',
  'please_provide_nominee_information': 'Please provide the nominee information.',
  'nominee_aadhaar_number': 'Nominee Aadhaar Number',
  'nominee_pan_number': 'Nominee PAN Number',
  'upload_nominee_aadhaar': 'Upload Nominee Aadhaar',
  'upload_nominee_pan': 'Upload Nominee PAN',
  'nominee_aadhaar_front_photo': 'Upload Nominee Aadhaar Front Photo',
  'nominee_aadhaar_back_photo': 'Upload Nominee Aadhaar Back Photo',
  'nominee_passbook_cheque_photo': 'Upload Nominee Passbook/Cheque Photo',
  'rules_and_declaration': 'Rules & Declaration',
  'rule_info_correct': 'I confirm that all information provided by me is correct.',
  'rule_info_rejection': 'I understand that incorrect information may result in rejection of my registration.',
  'rule_provide_documents': 'I agree to provide the required documents when requested.',
  'rule_agree_foundation_terms': 'I agree to the terms and conditions of Parivar Suraksha Foundation.',
  'back': 'Back',
  'finish': 'Finish',
  'please_upload_profile_photo': 'Please upload profile photo',
  'please_enter_your_signature': 'Please enter your signature',
  'please_select_gender': 'Please select gender',
  'please_select_marital_status': 'Please select marital status',
  'please_upload_nominee_photo': 'Please upload nominee photo',
  'add_another_nominee': 'Add Another Nominee',
  'nominee_saved_successfully': 'Nominee saved successfully',
  'nominee_total_share': 'Total share is @total%.',
  'nominee_share_exceeds_limit': 'You have allocated @total% share, which is more than 100%.',
  'nominee_share_must_be_100': 'Total nominee share must equal 100% (currently @total%).',
  'information_saved_successfully': 'Information saved successfully',
  'registration_completed_successfully': 'Registration completed successfully',
  'retry': 'Retry',
  'could_not_load_options': 'Could not load @label options.',
  'age_years': '@age years',
  'age_years_months': '@years yrs @months mo',
  'please_select_option': 'Please select @label',
  'step_member': 'Member',
  'step_nominee': 'Nominee',
  'step_health': 'Health',
  'camera': 'Camera',
  'gallery': 'Gallery',
  'health_step_optional_note':
      'This section is optional for now — you can continue without filling it in.',

  // Application Preview screen (book-style review + PDF download)
  'photo': 'Photo',
  'not_provided': 'Not provided',
  'pdf_saved_successfully': 'PDF saved successfully',
  'pdf_save_cancelled': 'Save cancelled',
  'pdf_generation_failed': 'Could not create the PDF. Please try again.',
  'preparing_pdf': 'Preparing your PDF...',
  'swipe_to_view_pages': 'Swipe to turn the page',

  // Preview pages redesigned to mirror the printed application form
  'member_form_title': 'Scheme Beneficiary Member Form',
  'form_date': 'Date',
  'age_label': 'Age (years)',
  'member_no': 'Member No.',
  'father_husband_name': "Father / Husband's Name",
  'native_place': 'Native Place',
  'nominee_number': 'Nominee : @n',
  'nominee_share': 'Share %',
  'please_enter_nominee_share': 'Enter share',
  'yes': 'Yes',
  'no': 'No',
  'your_faithfully': 'Yours faithfully',
  'member_signature': "Member's Signature",
  'place_label': 'Place',
  'member_undertaking_text':
      'I, @name, declare with honesty that all information given by me is true and complete. If any false or misleading information is found, the Foundation may cancel my membership and benefits, which will be acceptable to me and my nominee. I have read and understood all the rules of the Parivar Suraksha scheme and accept them.',
  'health_declaration_title': 'Health Declaration Form',
  'health_declaration_intro':
      "General health questions (please answer 'Yes' or 'No', and give details if 'Yes')",
  'health_q_current_illness':
      'Are you currently suffering from any serious illness?',
  'health_q_current_illness_detail': 'Please specify the illness',
  'health_q_past_diseases':
      'Have you ever had any of the following diseases?',
  'disease_heart': 'Heart Disease',
  'disease_heart_attack': 'Heart Attack',
  'disease_bp': 'High Blood Pressure',
  'disease_diabetes': 'Diabetes',
  'disease_asthma': 'Asthma / Breathing problem',
  'disease_tb': 'TB (Tuberculosis)',
  'disease_cancer': 'Cancer / Tumor',
  'disease_liver_kidney': 'Liver / Kidney disease',
  'disease_hiv': 'HIV / AIDS',
  'disease_other_infectious': 'Other serious infectious disease',
  'disease_stroke': 'Stroke / Paralysis',
  'disease_mental': 'Psychological disorder / Depression / Anxiety',
  'disease_hereditary': 'Any hereditary illness',
  'disease_other': 'Other',
  'health_hereditary_detail': 'Please specify the hereditary illness',
  'health_q_surgery':
      'Have you ever had any operation/surgery? If yes, which surgery and when',
  'health_q_surgery_detail': 'Which surgery, and when',
  'health_q_surgery_date': 'Surgery date',
  'health_q_medication':
      'Are you currently on any regular medication? If yes, which',
  'health_q_medication_detail': 'Which medication',
  'health_q_allergy':
      'Do you have any allergy (medicine/food/dust)? If yes, details',
  'health_q_allergy_detail': 'Allergy details',
  'health_detail_required': 'Please complete: @label',
  'health_q_tobacco': 'Do you use tobacco / beedi / cigarette?',
  'health_q_alcohol': 'Do you have an alcohol addiction?',
  'health_q_drugs': 'Do you use intoxicants / drugs?',
  'health_q_other': 'Any other details',
  'health_declare_text':
      'I, the undersigned, declare that all the information given above is true and complete to the best of my knowledge. If I have hidden or falsely given any information, the Foundation will have the full right to cancel my membership or claim.',
  'undertaking_title': 'Undertaking',
  'undertaking_text':
      'I, the undersigned, declare myself a member of the Parivar Suraksha Kavach scheme, and I and my nominee have read, understood and accepted this agreement and all the terms and conditions of the scheme. The information and evidence given by me and my nominee are true. The financial assistance payable after my demise will be given only to the nominee declared by me. I am bound to keep my membership active by continuously replenishing the savings account, contributing on the demise of other members, and fulfilling my responsibility towards spreading the service.',

  // Registration Pending screen — exit confirmation (back press / app
  // close on this screen has nowhere to go, since Home is reserved for an
  // approved member — see RegistrationPendingScreen).
  'exit_app': 'Exit app',
  'exit_app_message': 'Do you want to exit the app? You can come back anytime to check your approval status.',

  // Short, single-line validation messages for AppValidators — kept
  // compact in all 3 languages so they fit under a half-width field
  // without wrapping (see the share/village field-size complaints).
  'invalid_name': 'Enter a valid name',
  'mobile_number_field_required': 'Enter mobile number',
  'invalid_mobile_number': 'Enter valid 10-digit number',
  'enter_aadhaar_number': 'Enter Aadhaar number',
  'invalid_aadhaar_number': 'Aadhaar must be 12 digits',
  'enter_pan_number': 'Enter PAN number',
  'invalid_pan_number': 'Enter valid PAN number',
  'select_date': 'Select date',
  'ok': 'OK',
  'invalid_date_error': 'Enter a valid date',
  'date_out_of_range_error': 'Please select a date within the allowed range',
  'invalid_village_format': 'Letters, numbers, , and - only',

  // Toast messages that were hardcoded English regardless of selected
  // app language — now routed through .tr like every other user-facing
  // string on this screen.
  'field_translation_failed': '@label could not be translated. Please check your connection and try again.',
  'member_not_found_error': 'Member not found. Please restart registration.',
  'please_upload_aadhaar_photo': 'Please upload Aadhaar photo',
  'please_upload_aadhaar_back_photo': 'Please upload Aadhaar back photo',
  'please_upload_pan_photo': 'Please upload PAN card photo',
  'please_select_valid_dob': 'Please select a valid date of birth',
  'could_not_load_gender_marital_status_options': 'Could not load gender/marital status options. Pull to retry.',
  'please_upload_nominee_aadhaar_front_photo': 'Please upload nominee Aadhaar front photo',
  'please_upload_nominee_aadhaar_back_photo': 'Please upload nominee Aadhaar back photo',
  'please_upload_nominee_passbook_cheque_photo': 'Please upload nominee passbook/cheque photo',

  // ------------------------------------------------------------
  // Login screen
  // ------------------------------------------------------------
  'login_screen_subtitle': 'Sign in to continue to your account',
  'password': 'Password',
  'enter_password': 'Enter your password',
  'password_field_required': 'Please enter your password',
  'invalid_login_password': '4 capital letters + 4 digits',
  'login_successful': 'Login successful',
  'login_failed': 'Login failed. Please try again.',
  'dont_have_account': "Don't have an account?",
};

const registrationHi = <String, String>{
  'step': 'चरण', 'personal_information': 'व्यक्तिगत जानकारी', 'personal_information_hint': 'अपने दस्तावेज़ों के अनुसार जानकारी दर्ज करें।', 'date_of_birth': 'जन्म तिथि', 'address': 'पता', 'aadhaar_number': 'आधार नंबर', 'gender': 'लिंग', 'male': 'पुरुष', 'female': 'महिला', 'other': 'अन्य', 'profile_photo': 'प्रोफ़ाइल फ़ोटो अपलोड करें', 'aadhaar_photo': 'आधार कार्ड फ़ोटो अपलोड करें', 'file_selected': 'फ़ाइल चुनी गई', 'field_required': 'यह फ़ील्ड आवश्यक है', 'invalid_number': 'मान्य नंबर दर्ज करें', 'nominee_details': 'वारिस का विवरण', 'nominee_hint': 'लाभ के लिए वारिस जोड़ें।', 'nominee_name': 'वारिस का नाम', 'relationship': 'रिश्ता', 'nominee_note': 'वारिस का विवरण बाद में सहायता से बदला जा सकता है।', 'confirm_information': 'अपनी जानकारी की पुष्टि करें', 'confirm_information_hint': 'पूर्वावलोकन से पहले सभी जानकारी जाँचें।', 'nominee_will_be_added': 'वारिस अगले चरण में जोड़ा जाएगा', 'agree_terms': 'मैं जानकारी की पुष्टि करता/करती हूँ और योजना की शर्तों से सहमत हूँ।', 'accept_terms_error': 'आगे बढ़ने के लिए शर्तें स्वीकार करें।', 'required': 'आवश्यक', 'preview_application': 'आवेदन देखें', 'application_preview': 'आवेदन पूर्वावलोकन', 'download_pdf': 'पीडीएफ डाउनलोड करें', 'download_from_server': 'मूल पीडीएफ जमा करने के बाद सर्वर से डाउनलोड होगी।', 'complete_registration': 'पंजीकरण पूरा करें', 'beneficiary_application': 'लाभार्थी आवेदन', 'page_count': 'पृष्ठ @page / @total', 'declaration': 'घोषणा', 'declaration_text': 'मैं घोषणा करता/करती हूँ कि आवेदन में दी गई जानकारी सही और पूर्ण है।', 'registration_submitted': 'पंजीकरण जमा हो गया!', 'registration_submitted_hint': 'बधाई। आपका आवेदन अनुमोदन के लिए भेज दिया गया है।', 'approval_pending': 'आपका आवेदन समीक्षा में है', 'approval_pending_hint': 'प्रशासक की मंजूरी मिलते ही हम आपको सूचित करेंगे।', 'approval_time': 'अनुमोदन समय', 'approval_time_value': 'आमतौर पर 2-3 कार्य दिवस', 'support_contact': 'सहायता के लिए फाउंडेशन सहायता दल से संपर्क करें।', 'support_office_hours_title': 'कार्यालय समय', 'support_office_hours_morning': 'सुबह: 9:30 से 1:30', 'support_office_hours_afternoon': 'शाम: 4:00 से 9:30', 'support_contact_office_name': 'कार्यालय', 'support_contact_1_name': 'भरत वारिया', 'support_contact_2_name': 'बिपिन घोघारी', 'call': 'कॉल करें', 'whatsapp': 'व्हाट्सएप', 'could_not_open_app_error': 'इस कार्य के लिए ऐप नहीं खुल सका।',

  // Member registration screen (step-1 UI + nominee + rules sub-steps)
  'member_registration': 'सदस्य पंजीकरण',
  'full_name': 'पूरा नाम',
  'full_name_hint': 'पहला नाम, पिता का नाम और उपनाम दर्ज करें',
  // "Middle name" is written as "पिता का नाम" (father's name) here, not a
  // literal translation of "middle" — in Hindi/Gujarati naming
  // convention that middle slot IS the father's given name, so this
  // reads naturally instead of a confusing literal "middle" translation.
  'full_name_format_error': 'पहला नाम, पिता का नाम और उपनाम दर्ज करें।',
  'father_name': 'पिता का नाम',
  'father_name_hint': 'पहला नाम और उपनाम दर्ज करें',
  'father_name_format_error': 'पहला नाम और उपनाम दर्ज करें।',
  'mobile_number': 'मोबाइल नंबर',
  'mobile_number_2': 'मोबाइल नंबर 2',
  'village': 'गांव',
  'taluka': 'तालुका',
  'district': 'जिला',
  'state': 'राज्य',
  'occupation': 'व्यवसाय',
  'marital_status': 'वैवाहिक स्थिति',
  'address_details': 'पता विवरण',
  'identity_documents': 'पहचान दस्तावेज़',
  'pan_number': 'पैन नंबर',
  'upload_pan_card': 'पैन कार्ड अपलोड करें',
  'aadhaar_back_photo': 'आधार कार्ड पीछे की फ़ोटो अपलोड करें',
  'tap_to_upload': 'अपलोड करने के लिए टैप करें',
  'tap_to_upload_image': 'फ़ोटो अपलोड करने के लिए टैप करें',
  'signature': 'हस्ताक्षर',
  'your_signature': 'आपका हस्ताक्षर',
  'clear': 'साफ़ करें',
  'save_signature': 'हस्ताक्षर सहेजें',
  'tap_to_enter_signature': 'हस्ताक्षर करने के लिए टैप करें',
  'nominee_photo': 'वारिस की फ़ोटो',
  'please_provide_nominee_information': 'कृपया वारिस की जानकारी दर्ज करें।',
  'nominee_aadhaar_number': 'वारिस का आधार नंबर',
  'nominee_pan_number': 'वारिस का पैन नंबर',
  'upload_nominee_aadhaar': 'वारिस का आधार अपलोड करें',
  'upload_nominee_pan': 'वारिस का पैन अपलोड करें',
  'nominee_aadhaar_front_photo': 'वारिस के आधार कार्ड की आगे की फ़ोटो अपलोड करें',
  'nominee_aadhaar_back_photo': 'वारिस के आधार कार्ड की पीछे की फ़ोटो अपलोड करें',
  'nominee_passbook_cheque_photo': 'वारिस की पासबुक/चेक फ़ोटो अपलोड करें',
  'rules_and_declaration': 'नियम एवं घोषणा',
  'rule_info_correct': 'मैं पुष्टि करता/करती हूं कि मेरे द्वारा दी गई सभी जानकारी सही है।',
  'rule_info_rejection': 'मैं समझता/समझती हूं कि गलत जानकारी देने पर मेरा पंजीकरण अस्वीकार किया जा सकता है।',
  'rule_provide_documents': 'मैं मांगे जाने पर आवश्यक दस्तावेज़ प्रस्तुत करने के लिए सहमत हूं।',
  'rule_agree_foundation_terms': 'मैं परिवार सुरक्षा फाउंडेशन के नियम एवं शर्तों से सहमत हूं।',
  'back': 'वापस',
  'finish': 'समाप्त करें',
  'please_upload_profile_photo': 'कृपया प्रोफ़ाइल फ़ोटो अपलोड करें',
  'please_enter_your_signature': 'कृपया अपना हस्ताक्षर करें',
  'please_select_gender': 'कृपया लिंग चुनें',
  'please_select_marital_status': 'कृपया वैवाहिक स्थिति चुनें',
  'please_upload_nominee_photo': 'कृपया वारिस की फ़ोटो अपलोड करें',
  'add_another_nominee': 'एक और वारिस जोड़ें',
  'nominee_saved_successfully': 'वारिस सफलतापूर्वक सहेजा गया',
  'nominee_total_share': 'कुल हिस्सा @total% है।',
  'nominee_share_exceeds_limit': 'आपने @total% हिस्सा दिया है, जो 100% से अधिक है।',
  'nominee_share_must_be_100': 'कुल वारिस हिस्सा 100% होना चाहिए (अभी @total%)।',
  'information_saved_successfully': 'जानकारी सफलतापूर्वक सहेजी गई',
  'registration_completed_successfully': 'पंजीकरण सफलतापूर्वक पूर्ण हुआ',
  'retry': 'पुनः प्रयास करें',
  'could_not_load_options': '@label विकल्प लोड नहीं हो सके।',
  'age_years': '@age वर्ष',
  'age_years_months': '@years वर्ष @months माह',
  'please_select_option': 'कृपया @label चुनें',
  'step_member': 'सदस्य',
  'step_nominee': 'वारिस',
  'step_health': 'स्वास्थ्य',
  'camera': 'कैमरा',
  'gallery': 'गैलरी',
  'health_step_optional_note':
      'यह भाग अभी वैकल्पिक है — आप इसे भरे बिना भी आगे बढ़ सकते हैं।',

  // Application Preview screen (book-style review + PDF download)
  'photo': 'फ़ोटो',
  'not_provided': 'उपलब्ध नहीं',
  'pdf_saved_successfully': 'पीडीएफ सफलतापूर्वक सहेजी गई',
  'pdf_save_cancelled': 'सहेजना रद्द किया गया',
  'pdf_generation_failed': 'पीडीएफ नहीं बन सकी। कृपया पुनः प्रयास करें।',
  'preparing_pdf': 'आपकी पीडीएफ तैयार की जा रही है...',
  'swipe_to_view_pages': 'पेज पलटने के लिए स्वाइप करें',

  // Preview pages redesigned to mirror the printed application form
  'member_form_title': 'योजना लाभार्थी सदस्य फॉर्म',
  'form_date': 'तारीख',
  'age_label': 'आयु (वर्ष)',
  'member_no': 'सदस्य क्र.',
  'father_husband_name': 'पिता / पति का नाम',
  'native_place': 'मूल निवास स्थान',
  'nominee_number': 'वारिस : @n',
  'nominee_share': 'हिस्सा %',
  'please_enter_nominee_share': 'हिस्सा दर्ज करें',
  'yes': 'हाँ',
  'no': 'ना',
  'your_faithfully': 'आपका विश्वासु',
  'member_signature': 'सदस्य के हस्ताक्षर',
  'place_label': 'स्थल',
  'member_undertaking_text':
      'मैं, @name, प्रामाणिकता पूर्वक घोषित करता/करती हूं कि मेरे द्वारा दी गई सारी जानकारी सही और पूर्ण है। कोई गलत/भ्रामक जानकारी देने पर फाउंडेशन मेरी सदस्यता और लाभ रद्द कर सकता है, जो मुझे तथा मेरे वारिस को स्वीकार्य रहेगा। मैंने परिवार सुरक्षा कवच की सभी नियमावली पढ़कर, समझकर स्वीकार की है।',
  'health_declaration_title': 'स्वास्थ्य घोषणा फॉर्म',
  'health_declaration_intro':
      "स्वास्थ्य संबंधी सामान्य प्रश्न (कृपया 'हाँ' या 'ना' लिखें और यदि 'हाँ' है तो विवरण दें)",
  'health_q_current_illness':
      'क्या आप वर्तमान में किसी गंभीर बीमारी से पीड़ित हैं?',
  'health_q_current_illness_detail': 'बीमारी का विवरण दें',
  'health_q_past_diseases':
      'क्या आपको कभी निम्नलिखित में से कोई बीमारी हुई है?',
  'disease_heart': 'हृदय रोग',
  'disease_heart_attack': 'हार्ट अटैक',
  'disease_bp': 'हाई ब्लड प्रेशर',
  'disease_diabetes': 'मधुमेह (डायबिटीज)',
  'disease_asthma': 'अस्थमा / सांस की तकलीफ',
  'disease_tb': 'टीबी (क्षय रोग)',
  'disease_cancer': 'कैंसर / ट्यूमर',
  'disease_liver_kidney': 'लिवर / किडनी रोग',
  'disease_hiv': 'एचआईवी / एड्स',
  'disease_other_infectious': 'अन्य गंभीर संक्रामक रोग',
  'disease_stroke': 'स्ट्रोक / लकवा',
  'disease_mental': 'मानसिक रोग / डिप्रेशन / एंग्जायटी',
  'disease_hereditary': 'कोई वंशानुगत बीमारी',
  'disease_other': 'अन्य',
  'health_hereditary_detail': 'वंशानुगत बीमारी का विवरण दें',
  'health_q_surgery':
      'क्या आपकी कभी कोई सर्जरी हुई है? यदि हाँ, तो कौन सी सर्जरी और कब',
  'health_q_surgery_detail': 'कौन सी सर्जरी, कब',
  'health_q_surgery_date': 'सर्जरी की तारीख',
  'health_q_medication':
      'क्या आप वर्तमान में कोई नियमित दवा लेते हैं? यदि हाँ तो कौन सी',
  'health_q_medication_detail': 'कौन सी दवा',
  'health_q_allergy':
      'क्या आपको कोई एलर्जी (दवा/भोजन/धूल) है? यदि हाँ तो विवरण',
  'health_q_allergy_detail': 'एलर्जी का विवरण',
  'health_detail_required': 'कृपया पूर्ण करें: @label',
  'health_q_tobacco': 'क्या आप तंबाकू / बीड़ी / सिगरेट का उपयोग करते हैं?',
  'health_q_alcohol': 'क्या आपको शराब की लत है?',
  'health_q_drugs': 'क्या आप नशीले पदार्थों / ड्रग्स का उपयोग करते हैं?',
  'health_q_other': 'कोई अन्य विवरण',
  'health_declare_text':
      'मैं, नीचे हस्ताक्षरकर्ता, घोषित करता/करती हूं कि ऊपर दी गई सारी जानकारी मेरी जानकारी के अनुसार सही और पूर्ण है। यदि मैंने कोई जानकारी छुपाई या गलत दी है, तो फाउंडेशन को मेरी सदस्यता या दावा रद्द करने का पूर्ण अधिकार होगा।',
  'undertaking_title': 'वचनबद्धता',

  // Registration Pending screen — exit confirmation
  'exit_app': 'ऐप बंद करें',
  'exit_app_message': 'क्या आप ऐप बंद करना चाहते हैं? आप अपनी स्वीकृति की स्थिति जांचने के लिए कभी भी वापस आ सकते हैं।',

  'undertaking_text':
      'मैं, नीचे हस्ताक्षरकर्ता, स्वयं को परिवार सुरक्षा कवच योजना का सदस्य घोषित करता/करती हूं, और मैंने तथा मेरे वारिस ने यह करार तथा योजना की सभी शर्तें और नियम पढ़कर, समझकर स्वीकार किए हैं। मेरे तथा मेरे वारिस द्वारा दी गई जानकारी और प्रमाण सही हैं। मेरे निधन के बाद मिलने वाली आर्थिक सहायता केवल मेरे द्वारा घोषित वारिस को ही मिलेगी। मैं अपनी सदस्यता सक्रिय रखने के लिए बचत खाते की निरंतर पूर्ति करने, अन्य सदस्यों के निधन पर योगदान देने तथा सेवा प्रचार की जिम्मेदारी पूरी करने के लिए बाध्य हूं।',

  // Short, single-line validation messages for AppValidators.
  'invalid_name': 'मान्य नाम दर्ज करें',
  'mobile_number_field_required': 'मोबाइल नंबर दर्ज करें',
  'invalid_mobile_number': 'मान्य 10 अंकों का नंबर दर्ज करें',
  'enter_aadhaar_number': 'आधार नंबर दर्ज करें',
  'invalid_aadhaar_number': 'आधार 12 अंकों का होना चाहिए',
  'enter_pan_number': 'पैन नंबर दर्ज करें',
  'invalid_pan_number': 'मान्य पैन नंबर दर्ज करें',
  'select_date': 'तारीख चुनें',
  'ok': 'ठीक है',
  'invalid_date_error': 'मान्य तारीख दर्ज करें',
  'date_out_of_range_error': 'कृपया अनुमत सीमा के भीतर तारीख चुनें',
  'invalid_village_format': 'केवल अक्षर, अंक, , और - मान्य',

  'field_translation_failed': '@label अनुवादित नहीं हो सका। कृपया अपना कनेक्शन जाँचें और फिर से प्रयास करें।',
  'member_not_found_error': 'सदस्य नहीं मिला। कृपया पंजीकरण फिर से शुरू करें।',
  'please_upload_aadhaar_photo': 'कृपया आधार फ़ोटो अपलोड करें',
  'please_upload_aadhaar_back_photo': 'कृपया आधार पीछे की फ़ोटो अपलोड करें',
  'please_upload_pan_photo': 'कृपया पैन कार्ड फ़ोटो अपलोड करें',
  'please_select_valid_dob': 'कृपया मान्य जन्म तिथि चुनें',
  'could_not_load_gender_marital_status_options': 'लिंग/वैवाहिक स्थिति विकल्प लोड नहीं हो सके। रीट्राई के लिए खींचें।',
  'please_upload_nominee_aadhaar_front_photo': 'कृपया वारिस की आधार आगे की फ़ोटो अपलोड करें',
  'please_upload_nominee_aadhaar_back_photo': 'कृपया वारिस की आधार पीछे की फ़ोटो अपलोड करें',
  'please_upload_nominee_passbook_cheque_photo': 'कृपया वारिस की पासबुक/चेक फ़ोटो अपलोड करें',

  // ------------------------------------------------------------
  // Login screen
  // ------------------------------------------------------------
  'login_screen_subtitle': 'अपने खाते में जारी रखने के लिए साइन इन करें',
  'password': 'पासवर्ड',
  'enter_password': 'अपना पासवर्ड दर्ज करें',
  'password_field_required': 'कृपया अपना पासवर्ड दर्ज करें',
  'invalid_login_password': '4 बड़े अक्षर + 4 अंक',
  'login_successful': 'लॉगिन सफल',
  'login_failed': 'लॉगिन असफल रहा। कृपया पुनः प्रयास करें।',
  'dont_have_account': 'खाता नहीं है?',
};

const registrationGu = <String, String>{
  'step': 'પગલું', 'personal_information': 'વ્યક્તિગત માહિતી', 'personal_information_hint': 'તમારા દસ્તાવેજ મુજબ વિગતો દાખલ કરો.', 'date_of_birth': 'જન્મ તારીખ', 'address': 'સરનામું', 'aadhaar_number': 'આધાર નંબર', 'gender': 'લિંગ', 'male': 'પુરુષ', 'female': 'સ્ત્રી', 'other': 'અન્ય', 'profile_photo': 'પ્રોફાઇલ ફોટો અપલોડ કરો', 'aadhaar_photo': 'આધાર કાર્ડ ફોટો અપલોડ કરો', 'file_selected': 'ફાઇલ પસંદ થઈ', 'field_required': 'આ ફિલ્ડ જરૂરી છે', 'invalid_number': 'માન્ય નંબર દાખલ કરો', 'nominee_details': 'વારસદારની વિગતો', 'nominee_hint': 'લાભ માટે વારસદાર ઉમેરો.', 'nominee_name': 'વારસદારનું નામ', 'relationship': 'સંબંધ', 'nominee_note': 'વારસદારની વિગતો પછી સપોર્ટ દ્વારા બદલી શકાય છે.', 'confirm_information': 'તમારી માહિતી ચકાસો', 'confirm_information_hint': 'પૂર્વાવલોકન પહેલાં બધી વિગતો તપાસો.', 'nominee_will_be_added': 'વારસદાર આગળના પગલામાં ઉમેરાશે', 'agree_terms': 'હું માહિતી સાચી હોવાની ખાતરી કરું છું અને યોજનાની શરતો સ્વીકારું છું.', 'accept_terms_error': 'આગળ વધવા માટે શરતો સ્વીકારો.', 'required': 'જરૂરી', 'preview_application': 'અરજીનું પૂર્વાવલોકન', 'application_preview': 'અરજી પૂર્વાવલોકન', 'download_pdf': 'PDF ડાઉનલોડ કરો', 'download_from_server': 'મૂળ PDF સબમિટ કર્યા પછી સર્વર પરથી ડાઉનલોડ થશે.', 'complete_registration': 'રજીસ્ટ્રેશન પૂર્ણ કરો', 'beneficiary_application': 'લાભાર્થી અરજી', 'page_count': 'પૃષ્ઠ @page / @total', 'declaration': 'ઘોષણા', 'declaration_text': 'હું જાહેર કરું છું કે આ અરજીમાં આપેલી માહિતી સાચી અને સંપૂર્ણ છે.', 'registration_submitted': 'રજીસ્ટ્રેશન સબમિટ થયું!', 'registration_submitted_hint': 'અભિનંદન. તમારી અરજી મંજૂરી માટે મોકલવામાં આવી છે.', 'approval_pending': 'તમારી અરજી સમીક્ષા હેઠળ છે', 'approval_pending_hint': 'એડમિન મંજૂરી આપશે ત્યારે અમે તમને જાણ કરીશું.', 'approval_time': 'મંજૂરીનો સમય', 'approval_time_value': 'સામાન્ય રીતે 2-3 કાર્ય દિવસ', 'support_contact': 'મદદ માટે ફાઉન્ડેશન સપોર્ટ ટીમનો સંપર્ક કરો.', 'support_office_hours_title': 'ઓફિસ સમય', 'support_office_hours_morning': 'સવારે: 9:30 થી 1:30', 'support_office_hours_afternoon': 'બપોરે: 4:00 થી 9:30', 'support_contact_office_name': 'ઓફિસ', 'support_contact_1_name': 'ભરત વરિયા', 'support_contact_2_name': 'બિપિન ઘોઘારી', 'call': 'કૉલ કરો', 'whatsapp': 'વોટ્સએપ', 'could_not_open_app_error': 'આ ક્રિયા માટે એપ ખોલી શકાઈ નથી.',

  // Member registration screen (step-1 UI + nominee + rules sub-steps)
  'member_registration': 'સભ્ય નોંધણી',
  'full_name': 'પૂરું નામ',
  'full_name_hint': 'પ્રથમ નામ, પિતાનું નામ અને અટક દાખલ કરો',
  // Same reasoning as the Hindi block above — "પિતાનું નામ" (father's
  // name) instead of a literal "middle" translation.
  'full_name_format_error': 'પ્રથમ નામ, પિતાનું નામ અને અટક દાખલ કરો.',
  'father_name': 'પિતાનું નામ',
  'father_name_hint': 'પ્રથમ નામ અને અટક દાખલ કરો',
  'father_name_format_error': 'પ્રથમ નામ અને અટક દાખલ કરો.',
  'mobile_number': 'મોબાઇલ નંબર',
  'mobile_number_2': 'મોબાઇલ નંબર 2',
  'village': 'મૂળ વતન',
  'taluka': 'તાલુકા',
  'district': 'જિલ્લો',
  'state': 'રાજ્ય',
  'occupation': 'વ્યવસાય',
  'marital_status': 'વૈવાહિક સ્થિતિ',
  'address_details': 'સરનામાની વિગતો',
  'identity_documents': 'ઓળખ દસ્તાવેજો',
  'pan_number': 'પાન નંબર',
  'upload_pan_card': 'પાન કાર્ડ અપલોડ કરો',
  'aadhaar_back_photo': 'આધાર કાર્ડ પાછળનો ફોટો અપલોડ કરો',
  'tap_to_upload': 'અપલોડ કરવા ટેપ કરો',
  'tap_to_upload_image': 'ફોટો અપલોડ કરવા ટેપ કરો',
  'signature': 'સહી',
  'your_signature': 'તમારી સહી',
  'clear': 'સાફ કરો',
  'save_signature': 'સહી સેવ કરો',
  'tap_to_enter_signature': 'સહી કરવા ટેપ કરો',
  'nominee_photo': 'વારસદારનો ફોટો',
  'please_provide_nominee_information': 'કૃપા કરીને વારસદારની માહિતી આપો.',
  'nominee_aadhaar_number': 'વારસદારનો આધાર નંબર',
  'nominee_pan_number': 'વારસદારનો પાન નંબર',
  'upload_nominee_aadhaar': 'વારસદારનું આધાર અપલોડ કરો',
  'upload_nominee_pan': 'વારસદારનું પાન અપલોડ કરો',
  'nominee_aadhaar_front_photo': 'વારસદારના આધાર કાર્ડનો આગળનો ફોટો અપલોડ કરો',
  'nominee_aadhaar_back_photo': 'વારસદારના આધાર કાર્ડનો પાછળનો ફોટો અપલોડ કરો',
  'nominee_passbook_cheque_photo': 'વારસદારનું પાસબુક/ચેક ફોટો અપલોડ કરો',
  'rules_and_declaration': 'નિયમો અને ઘોષણા',
  'rule_info_correct': 'હું પુષ્ટિ કરું છું કે મેં આપેલી બધી માહિતી સાચી છે.',
  'rule_info_rejection': 'હું સમજું છું કે ખોટી માહિતીના કારણે મારી નોંધણી નકારી શકાય છે.',
  'rule_provide_documents': 'હું જરૂર પડ્યે જરૂરી દસ્તાવેજો આપવા સંમત છું.',
  'rule_agree_foundation_terms': 'હું પરિવાર સુરક્ષા ફાઉન્ડેશનના નિયમો અને શરતો સાથે સંમત છું.',
  'back': 'પાછળ',
  'finish': 'પૂર્ણ કરો',
  'please_upload_profile_photo': 'કૃપા કરીને પ્રોફાઇલ ફોટો અપલોડ કરો',
  'please_enter_your_signature': 'કૃપા કરીને તમારી સહી કરો',
  'please_select_gender': 'કૃપા કરીને લિંગ પસંદ કરો',
  'please_select_marital_status': 'કૃપા કરીને વૈવાહિક સ્થિતિ પસંદ કરો',
  'please_upload_nominee_photo': 'કૃપા કરીને વારસદારનો ફોટો અપલોડ કરો',
  'add_another_nominee': 'બીજો વારસદાર ઉમેરો',
  'nominee_saved_successfully': 'વારસદાર સફળતાપૂર્વક સેવ થયો',
  'nominee_total_share': 'કુલ હિસ્સો @total% છે.',
  'nominee_share_exceeds_limit': 'તમે @total% હિસ્સો ફાળવ્યો છે, જે 100% કરતાં વધુ છે.',
  'nominee_share_must_be_100': 'કુલ વારસદાર હિસ્સો 100% હોવો જોઈએ (હાલમાં @total%).',
  'information_saved_successfully': 'માહિતી સફળતાપૂર્વક સેવ થઈ',
  'registration_completed_successfully': 'નોંધણી સફળતાપૂર્વક પૂર્ણ થઈ',
  'retry': 'ફરી પ્રયાસ કરો',
  'could_not_load_options': '@label વિકલ્પો લોડ કરી શકાયા નથી.',
  'age_years': '@age વર્ષ',
  'age_years_months': '@years વર્ષ @months મહિના',
  'please_select_option': 'કૃપા કરીને @label પસંદ કરો',
  'step_member': 'સભ્ય',
  'step_nominee': 'વારસદાર',
  'step_health': 'આરોગ્ય',
  'camera': 'કેમેરા',
  'gallery': 'ગેલેરી',
  'health_step_optional_note':
      'આ વિભાગ હાલ પૂરતો વૈકલ્પિક છે — તમે તેને ભર્યા વગર પણ આગળ વધી શકો છો.',

  // Application Preview screen (book-style review + PDF download)
  'photo': 'ફોટો',
  'not_provided': 'ઉપલબ્ધ નથી',
  'pdf_saved_successfully': 'PDF સફળતાપૂર્વક સેવ થઈ',
  'pdf_save_cancelled': 'સેવ કરવાનું રદ થયું',
  'pdf_generation_failed': 'PDF બનાવી શકાયું નહીં. કૃપા કરીને ફરી પ્રયાસ કરો.',
  'preparing_pdf': 'તમારું PDF તૈયાર થઈ રહ્યું છે...',
  'swipe_to_view_pages': 'પાનું ફેરવવા સ્વાઇપ કરો',

  // Preview pages redesigned to mirror the printed application form
  'member_form_title': 'યોજના લાભાર્થી સભ્યફોર્મ',
  'form_date': 'તારીખ',
  'age_label': 'ઉંમર વર્ષ',
  'member_no': 'સભ્ય નં',
  'father_husband_name': 'પિતા / પતિનું નામ',
  'native_place': 'મૂળ વતન',
  'nominee_number': 'વારસદાર : @n',
  'nominee_share': 'હિસ્સો %',
  'please_enter_nominee_share': 'હિસ્સો દાખલ કરો',
  'yes': 'હા',
  'no': 'ના',
  'your_faithfully': 'આપનો વિશ્વાસુ',
  'member_signature': 'સભ્યની સહી',
  'place_label': 'સ્થળ',
  'member_undertaking_text':
      'હું, @name, પ્રામાણિકતા પુર્વક જાહેર કરું છું કે, મારા દ્વારા આપાયેલી તમામ માહિતી સાચી અને પૂર્ણ છે, કોઈ ખોટી/ભ્રામક માહિતી આપી હોવા પર ફાઉન્ડેશન મારુ સભ્યપદ અને લાભો રદ્દ કરી શકે છે, જે મને તથા મારા વારસદારને સ્વીકાર્ય રહેશે, મેં પરિવાર સુરક્ષા કવચની તમામ નિયમાવલી ને વાંચી, સમજીને સ્વીકાર કરું છું.',
  'health_declaration_title': 'હેલ્થ ડિકલેરેશન ફોર્મ',
  'health_declaration_intro':
      "આરોગ્ય અંગે સામાન્ય પ્રશ્નો (કૃપા કરીને ''હા'' અથવા ''ના'' લખશો અને જો ''હા'' હોય તો વિગત આપશો )",
  'health_q_current_illness':
      'શું તમે હાલમાં કોઈ ગંભીર બિમારીથી પીડાઈ રહ્યાં છો?',
  'health_q_current_illness_detail': 'બિમારીની વિગત આપો',
  'health_q_past_diseases': 'શું તમને ક્યારેય નીચેના રોગો થયા છે?',
  'disease_heart': 'હૃદય રોગ',
  'disease_heart_attack': 'હાર્ટ એટેક',
  'disease_bp': 'હાઈ બ્લડ પ્રેશર',
  'disease_diabetes': 'ડાયાબિટીસ',
  'disease_asthma': 'અસ્થમા/શ્વાસની તકલીફ',
  'disease_tb': 'ટીબી (ક્ષયરોગ)',
  'disease_cancer': 'કેન્સર/ટ્યુમર',
  'disease_liver_kidney': 'લિવર રોગ/કિડની રોગ',
  'disease_hiv': 'HIV/AIDS',
  'disease_other_infectious': 'અન્ય ગંભીર ચેપી રોગ',
  'disease_stroke': 'સ્ટ્રોક / પેરાલિસિસ',
  'disease_mental': 'મનોવૈજ્ઞાનિક રોગ / ડિપ્રેશન / એન્ઝાયટી',
  'disease_hereditary': 'કોઈ વારસાગત બિમારી',
  'disease_other': 'અન્ય',
  'health_hereditary_detail': 'વારસાગત બિમારીની વિગત આપો',
  'health_q_surgery':
      'શુ તમને ક્યારેય કોઈ ઓપરેશન / સર્જરી થઈ છે - જો હા, તો કઈ સર્જરી અને ક્યારે',
  'health_q_surgery_detail': 'કઈ સર્જરી, ક્યારે',
  'health_q_surgery_date': 'સર્જરીની તારીખ',
  'health_q_medication':
      'શુ તમે હાલમાં કોઈ દવા નિયમિત લો છો? - જો હા તો કઈ દવા',
  'health_q_medication_detail': 'કઈ દવા',
  'health_q_allergy':
      'શુ તમને કોઈ એલર્જી (દવા / ખોરાક / ધુળ) છે ? - જો હા વિગત',
  'health_q_allergy_detail': 'એલર્જીની વિગત',
  'health_detail_required': 'કૃપા કરીને પૂર્ણ કરો: @label',
  'health_q_tobacco': 'તમાકુ/બીડી/સિગારેટ નો ઉપયોગ કરો છો.',
  'health_q_alcohol': 'શુ તમને દારૂનું વ્યસન છે.',
  'health_q_drugs': 'શુ તમે નશીલા પદાર્થો /ડ્રગ્સનો ઉપયોગ કરો છો?',
  'health_q_other': 'અન્ય કોઈ વિગત',
  'health_declare_text':
      'નીચે સહી કરનાર, જાહેર કરું છું કે ઉપર આપેલી તમામ માહિતી મારી જાણ મુજબ સાચી અને સંપૂર્ણ છે, જો હું કોઈ માહિતી છુપાવી હોય અથવા ખોટી આપેલી હોય તો ફાઉન્ડેશનને મારુ સભ્યપદ કે કલેઈમ રદ કરવાનો સંપૂર્ણ અધિકાર રહેશે.',
  'undertaking_title': 'જાહેર ખબર',

  // Registration Pending screen — exit confirmation
  'exit_app': 'એપ બંધ કરો',
  'exit_app_message': 'શું તમે એપ બંધ કરવા માંગો છો? તમે તમારી મંજૂરીની સ્થિતિ ચકાસવા માટે ગમે ત્યારે પાછા આવી શકો છો.',
  'undertaking_text':
      'નીચે સહી કરનાર પરિવાર સુરક્ષા કવચ યોજનાનો સભ્ય જાહેર કરું છું, કે આ કરાર તથા યોજનાની તમામ શરતો અને નિયમો મેં અને મારા વારસદારે વાંચી, સમજીને સ્વીકાર્યા છે. મારા અને મારા વારસદાર દ્વારા આપવામાં આવેલી માહિતી અને પુરાવા સાચા છે. મારા અવસાન પછી મળવાપાત્ર આર્થિક સહાય માત્ર મારા દ્વારા જાહેર કરેલા વારસદારને જ મળશે. હું મારા સભ્ય પદને સક્રિય રાખવા માટે બચત ખાતાની સતત પૂર્તિ કરવા, અન્ય સભાસદોના અવસાન પર યોગદાન આપવા તથા સેવા પ્રચારની જવાબદારી પુરી કરવા બંધાયેલ છું.',

  // Short, single-line validation messages for AppValidators.
  'invalid_name': 'માન્ય નામ દાખલ કરો',
  'mobile_number_field_required': 'મોબાઇલ નંબર દાખલ કરો',
  'invalid_mobile_number': 'માન્ય 10 અંકનો નંબર દાખલ કરો',
  'enter_aadhaar_number': 'આધાર નંબર દાખલ કરો',
  'invalid_aadhaar_number': 'આધાર 12 અંકનો હોવો જોઈએ',
  'enter_pan_number': 'પાન નંબર દાખલ કરો',
  'invalid_pan_number': 'માન્ય પાન નંબર દાખલ કરો',
  'select_date': 'તારીખ પસંદ કરો',
  'ok': 'બરાબર',
  'invalid_date_error': 'માન્ય તારીખ દાખલ કરો',
  'date_out_of_range_error': 'કૃપા કરી માન્ય મર્યાદામાં તારીખ પસંદ કરો',
  'invalid_village_format': 'ફક્ત અક્ષર, અંક, , અને - માન્ય',

  'field_translation_failed': '@label અનુવાદિત થઈ શક્યું નથી. કૃપા કરીને તમારું કનેક્શન ચકાસો અને ફરી પ્રયાસ કરો.',
  'member_not_found_error': 'સભ્ય મળ્યો નથી. કૃપા કરીને નોંધણી ફરી શરૂ કરો.',
  'please_upload_aadhaar_photo': 'કૃપા કરીને આધાર ફોટો અપલોડ કરો',
  'please_upload_aadhaar_back_photo': 'કૃપા કરીને આધાર પાછળનો ફોટો અપલોડ કરો',
  'please_upload_pan_photo': 'કૃપા કરીને પાન કાર્ડ ફોટો અપલોડ કરો',
  'please_select_valid_dob': 'કૃપા કરીને માન્ય જન્મ તારીખ પસંદ કરો',
  'could_not_load_gender_marital_status_options': 'લિંગ/વૈવાહિક સ્થિતિ વિકલ્પો લોડ કરી શકાયા નથી. રીટ્રાય માટે ખેંચો.',
  'please_upload_nominee_aadhaar_front_photo': 'કૃપા કરીને વારસદારનો આધાર આગળનો ફોટો અપલોડ કરો',
  'please_upload_nominee_aadhaar_back_photo': 'કૃપા કરીને વારસદારનો આધાર પાછળનો ફોટો અપલોડ કરો',
  'please_upload_nominee_passbook_cheque_photo': 'કૃપા કરીને વારસદારનું પાસબુક/ચેક ફોટો અપલોડ કરો',

  // ------------------------------------------------------------
  // Login screen
  // ------------------------------------------------------------
  'login_screen_subtitle': 'તમારા ખાતામાં ચાલુ રાખવા માટે સાઇન ઇન કરો',
  'password': 'પાસવર્ડ',
  'enter_password': 'તમારો પાસવર્ડ દાખલ કરો',
  'password_field_required': 'કૃપા કરીને તમારો પાસવર્ડ દાખલ કરો',
  'invalid_login_password': '4 મોટા અક્ષર + 4 આંકડા',
  'login_successful': 'લૉગિન સફળ',
  'login_failed': 'લૉગિન નિષ્ફળ. કૃપા કરી ફરી પ્રયાસ કરો.',
  'dont_have_account': 'ખાતું નથી?',
};
